// js/jobs-data.js
const jobs = [
  {
    id: 1,
    title: "Software Developer (LMIA Approved)",
    company: "MapleTech Solutions",
    location: "Toronto, Canada",
    visaType: "Canada Work Permit",
    description: "Develop and maintain enterprise web applications using Java, Spring Boot, and Angular. LMIA sponsorship provided with a clear path to permanent residency.",
    requirements: ["3+ years Java development", "Spring Boot", "SQL/NoSQL", "English CLB 7"],
    salary: "$75,000 - $90,000 CAD per year",
    applyBy: "2026-08-15",
    type: "Full-time"
  },
  {
    id: 2,
    title: "Registered Nurse (H-1B Sponsorship)",
    company: "American Care Hospitals",
    location: "Houston, USA",
    visaType: "USA H-1B Visa",
    description: "Provide high-quality patient care in the ICU and emergency room. H-1B sponsorship available for eligible international nurses.",
    requirements: ["Valid RN license", "NCLEX-RN certification", "2+ years hospital experience", "BLS/ACLS certification"],
    salary: "$65,000 - $80,000 USD per year",
    applyBy: "2026-07-30",
    type: "Full-time"
  },
  {
    id: 3,
    title: "Long Haul Truck Driver",
    company: "MapleLeaf Logistics",
    location: "Calgary, Canada",
    visaType: "Canada Work Permit",
    description: "Transport goods across Canada and the USA. Must have a valid AZ license. Work permit sponsorship available.",
    requirements: ["Valid AZ or Class 1 license", "2+ years long-haul experience", "Clean driving record", "English CLB 5"],
    salary: "$60,000 - $70,000 CAD per year",
    applyBy: "2026-09-01",
    type: "Full-time"
  },
  {
    id: 4,
    title: "Civil Engineer (Express Entry Eligible)",
    company: "Great Northern Infrastructure",
    location: "Vancouver, Canada",
    visaType: "Canada Work Permit / Express Entry",
    description: "Design and oversee construction of roads and bridges. Employer will support LMIA or PNP application.",
    requirements: ["Bachelor's degree in Civil Engineering", "5+ years experience", "P.Eng license (or eligible)", "IELTS 6.5+"],
    salary: "$85,000 - $105,000 CAD per year",
    applyBy: "2026-08-20",
    type: "Full-time"
  },
  {
    id: 5,
    title: "HVAC Technician (H-2B Visa)",
    company: "SunState Cooling",
    location: "Miami, USA",
    visaType: "USA H-2B Visa",
    description: "Install, maintain, and repair heating, ventilation, and air conditioning systems. Seasonal H-2B visa offered for experienced technicians.",
    requirements: ["2+ years HVAC experience", "EPA certification", "Valid driver's license", "English conversational"],
    salary: "$22 - $28 USD per hour",
    applyBy: "2026-06-30",
    type: "Full-time (Seasonal)"
  },
  {
    id: 6,
    title: "Data Analyst (LMIA Approved)",
    company: "TrueNorth Analytics",
    location: "Ottawa, Canada",
    visaType: "Canada Work Permit",
    description: "Analyze large datasets to support business decisions. Proficiency in Python, SQL, and Tableau required. LMIA approved.",
    requirements: ["2+ years data analysis", "Python/SQL", "Tableau/Power BI", "English CLB 7"],
    salary: "$70,000 - $85,000 CAD per year",
    applyBy: "2026-08-10",
    type: "Full-time"
  },
  {
    id: 7,
    title: "Chef de Partie (J-1 Visa)",
    company: "The Gourmet Group",
    location: "New York, USA",
    visaType: "USA J-1 Visa (Culinary Exchange)",
    description: "Prepare high-end international cuisine. J-1 visa for cultural exchange with potential transition to H-1B.",
    requirements: ["Culinary diploma or 5+ years experience", "Specialty cuisine knowledge", "Food safety certification", "English B1"],
    salary: "$45,000 - $55,000 USD per year",
    applyBy: "2026-07-15",
    type: "Full-time"
  },
  {
    id: 8,
    title: "Construction Labourer (LMIA)",
    company: "BuildRight Contractors",
    location: "Edmonton, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "General labour on residential and commercial construction sites. No formal education required. On-job training provided.",
    requirements: ["Physically fit", "Willing to work outdoors", "Basic English", "Previous construction experience a plus"],
    salary: "$22 - $25 CAD per hour",
    applyBy: "2026-07-31",
    type: "Full-time"
  },
  {
    id: 9,
    title: "Software Engineer (L-1 Intracompany)",
    company: "GlobalTech Corp",
    location: "Silicon Valley, USA",
    visaType: "USA L-1 Visa",
    description: "Internal transfer for senior software engineers from international offices. Must have worked for company for at least 1 year.",
    requirements: ["Employment with GlobalTech abroad for 1+ year", "Expertise in C++/Python", "Managerial or specialized knowledge", "Bachelor's degree"],
    salary: "$130,000 - $160,000 USD per year",
    applyBy: "2026-09-15",
    type: "Full-time"
  },
  {
    id: 10,
    title: "Farm Worker (H-2A Visa)",
    company: "GreenValley Farms",
    location: "California, USA",
    visaType: "USA H-2A Visa",
    description: "Seasonal work in fruit and vegetable harvesting, packing, and equipment operation. H-2A visa provided.",
    requirements: ["Experience in farming/harvesting", "Physically demanding work", "No specific language requirement", "Available for 6-9 months"],
    salary: "$17 - $20 USD per hour",
    applyBy: "2026-06-15",
    type: "Seasonal"
  },
  {
    id: 11,
    title: "Electrical Engineer (PNP Support)",
    company: "Ontario Power Solutions",
    location: "Toronto, Canada",
    visaType: "Canada Work Permit / Ontario PNP",
    description: "Design electrical systems for commercial buildings. Employer supports Provincial Nominee Program.",
    requirements: ["B.Sc. Electrical Engineering", "4+ years experience", "P.Eng eligibility", "IELTS 7.0"],
    salary: "$80,000 - $95,000 CAD per year",
    applyBy: "2026-08-05",
    type: "Full-time"
  },
  {
    id: 12,
    title: "Welder (LMIA Approved)",
    company: "SteelCraft Manufacturing",
    location: "Winnipeg, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "Welding and fabrication of metal components. CWB certification preferred. LMIA approved for skilled welders.",
    requirements: ["3+ years welding experience", "CWB or equivalent", "Ability to read blueprints", "English CLB 5"],
    salary: "$27 - $32 CAD per hour",
    applyBy: "2026-07-20",
    type: "Full-time"
  },
  {
    id: 13,
    title: "Physical Therapist (H-1B)",
    company: "RehabCare Clinics",
    location: "Chicago, USA",
    visaType: "USA H-1B Visa",
    description: "Provide physical therapy services in an outpatient clinic. Must be licensed or eligible for US licensure.",
    requirements: ["Doctor of Physical Therapy (DPT)", "State license (or eligible)", "2+ years experience", "English proficiency"],
    salary: "$75,000 - $90,000 USD per year",
    applyBy: "2026-08-01",
    type: "Full-time"
  },
  {
    id: 14,
    title: "Graphic Designer (TN Visa)",
    company: "Creative Edge Studio",
    location: "Los Angeles, USA",
    visaType: "USA TN Visa (Canadian/Mexican)",
    description: "Design branding, marketing materials, and digital assets. TN visa for qualified Canadian or Mexican citizens.",
    requirements: ["Graphic design degree or diploma", "3+ years experience", "Adobe Creative Suite", "Portfolio required"],
    salary: "$55,000 - $70,000 USD per year",
    applyBy: "2026-07-25",
    type: "Full-time"
  },
  {
    id: 15,
    title: "Hotel Manager (Express Entry)",
    company: "Prestige Hotels & Resorts",
    location: "Banff, Canada",
    visaType: "Canada Work Permit / Express Entry",
    description: "Oversee daily hotel operations, staff management, and guest satisfaction. Employer will support LMIA or PNP.",
    requirements: ["Diploma in Hotel Management", "5+ years experience", "Leadership skills", "English CLB 7"],
    salary: "$65,000 - $80,000 CAD per year",
    applyBy: "2026-08-30",
    type: "Full-time"
  },
  {
    id: 16,
    title: "Caregiver (Home Child Care Pilot)",
    company: "FamilyCare Connections",
    location: "Vancouver, Canada",
    visaType: "Canada Caregiver Pilot",
    description: "Provide in-home childcare for families. Eligible for permanent residence after 24 months under the pilot program.",
    requirements: ["Experience in childcare", "First Aid/CPR", "Criminal record check", "English CLB 4"],
    salary: "$16 - $18 CAD per hour",
    applyBy: "2026-09-05",
    type: "Full-time"
  },
  {
    id: 17,
    title: "Automotive Mechanic (H-2B)",
    company: "Speedy Auto Repairs",
    location: "Dallas, USA",
    visaType: "USA H-2B Visa",
    description: "Diagnose and repair vehicles. H-2B visa for qualified mechanics. Transition to permanent role possible.",
    requirements: ["3+ years mechanic experience", "ASE certification preferred", "Valid driver's license", "English conversational"],
    salary: "$20 - $25 USD per hour",
    applyBy: "2026-07-10",
    type: "Full-time"
  },
  {
    id: 18,
    title: "Accountant (LMIA)",
    company: "Northern Financial Group",
    location: "Halifax, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "Prepare financial statements, tax returns, and audits. CPA designation preferred. LMIA approved.",
    requirements: ["Bachelor's in Accounting", "3+ years experience", "CPA (or eligible)", "English CLB 7"],
    salary: "$60,000 - $75,000 CAD per year",
    applyBy: "2026-08-12",
    type: "Full-time"
  },
  {
    id: 19,
    title: "Plumber (LMIA Approved)",
    company: "FlowRight Plumbing",
    location: "Montreal, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "Install and repair plumbing systems in residential and commercial buildings. Red Seal certification a plus.",
    requirements: ["Journeyman plumber or 5+ years experience", "Knowledge of Canadian plumbing code", "English or French", "Valid driver's license"],
    salary: "$30 - $36 CAD per hour",
    applyBy: "2026-07-28",
    type: "Full-time"
  },
  {
    id: 20,
    title: "Marketing Manager (L-1 Visa)",
    company: "BrandWave International",
    location: "San Francisco, USA",
    visaType: "USA L-1 Visa",
    description: "Lead marketing campaigns for the North American market. Internal transfer from overseas office.",
    requirements: ["Currently employed by BrandWave abroad", "5+ years marketing experience", "Bachelor's degree", "English fluent"],
    salary: "$110,000 - $140,000 USD per year",
    applyBy: "2026-09-10",
    type: "Full-time"
  },
  {
    id: 21,
    title: "Carpenter (LMIA)",
    company: "CraftWood Construction",
    location: "Calgary, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "Framing, finishing, and custom woodwork. LMIA approved for skilled carpenters.",
    requirements: ["3+ years carpentry", "Red Seal or equivalent", "Ability to read plans", "English CLB 5"],
    salary: "$28 - $34 CAD per hour",
    applyBy: "2026-08-03",
    type: "Full-time"
  },
  {
    id: 22,
    title: "Restaurant Supervisor (J-1)",
    company: "FineDine Group",
    location: "Orlando, USA",
    visaType: "USA J-1 Visa",
    description: "Supervise front-of-house operations in a busy restaurant. J-1 cultural exchange visa.",
    requirements: ["Hospitality diploma or 3+ years experience", "Supervisory experience", "English intermediate", "Flexible schedule"],
    salary: "$35,000 - $42,000 USD per year",
    applyBy: "2026-07-05",
    type: "Full-time"
  },
  {
    id: 23,
    title: "Nurse Practitioner (H-1B)",
    company: "HealthFirst Clinics",
    location: "Boston, USA",
    visaType: "USA H-1B Visa",
    description: "Provide primary care services. Must hold Master's degree and national certification.",
    requirements: ["MSN degree", "NP certification", "State license or eligible", "2+ years experience"],
    salary: "$100,000 - $120,000 USD per year",
    applyBy: "2026-08-15",
    type: "Full-time"
  },
  {
    id: 24,
    title: "IT Support Specialist (TN Visa)",
    company: "TechAssist Corp",
    location: "Seattle, USA",
    visaType: "USA TN Visa",
    description: "Provide technical support for enterprise clients. TN visa for Canadian/Mexican citizens with related degree.",
    requirements: ["Diploma/Degree in IT", "2+ years experience", "CompTIA A+ or similar", "English fluent"],
    salary: "$50,000 - $65,000 USD per year",
    applyBy: "2026-08-10",
    type: "Full-time"
  },
  {
    id: 25,
    title: "Early Childhood Educator (PNP)",
    company: "Bright Stars Daycare",
    location: "Saskatoon, Canada",
    visaType: "Canada Work Permit / Saskatchewan PNP",
    description: "Plan and implement educational activities for children aged 2-5. Employer supports PNP application.",
    requirements: ["ECE diploma or degree", "1+ year experience", "First Aid", "English CLB 7"],
    salary: "$40,000 - $50,000 CAD per year",
    applyBy: "2026-08-20",
    type: "Full-time"
  },
  {
    id: 26,
    title: "Mechanical Engineer (LMIA)",
    company: "Precision Machinery Ltd.",
    location: "Edmonton, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "Design and improve mechanical systems for oil & gas sector. LMIA approved.",
    requirements: ["B.Sc. Mechanical Engineering", "4+ years experience", "P.Eng eligible", "English CLB 7"],
    salary: "$85,000 - $100,000 CAD per year",
    applyBy: "2026-08-18",
    type: "Full-time"
  },
  {
    id: 27,
    title: "Landscape Worker (H-2B)",
    company: "GreenScape Gardening",
    location: "Denver, USA",
    visaType: "USA H-2B Visa",
    description: "Maintain gardens, plant trees, and operate landscaping equipment. Seasonal H-2B visa.",
    requirements: ["1+ year landscaping experience", "Physically fit", "Driver's license a plus", "English basic"],
    salary: "$18 - $22 USD per hour",
    applyBy: "2026-06-25",
    type: "Seasonal"
  },
  {
    id: 28,
    title: "Pharmacy Technician (H-1B)",
    company: "MediCare Pharmacies",
    location: "Philadelphia, USA",
    visaType: "USA H-1B Visa",
    description: "Assist pharmacists in dispensing medications. Requires certification and experience.",
    requirements: ["Pharmacy Technician certification", "2+ years experience", "Attention to detail", "English fluent"],
    salary: "$35,000 - $45,000 USD per year",
    applyBy: "2026-07-20",
    type: "Full-time"
  },
  {
    id: 29,
    title: "Baker (LMIA)",
    company: "OvenFresh Bakery",
    location: "Mississauga, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "Prepare breads, pastries, and desserts. LMIA approved for experienced bakers.",
    requirements: ["3+ years bakery experience", "Knowledge of food safety", "Ability to work early mornings", "English CLB 4"],
    salary: "$18 - $22 CAD per hour",
    applyBy: "2026-07-30",
    type: "Full-time"
  },
  {
    id: 30,
    title: "Architect (E-2 Visa)",
    company: "DesignBuild USA",
    location: "Miami, USA",
    visaType: "USA E-2 Treaty Investor (if eligible)",
    description: "Design commercial structures. Firm may consider E-2 for qualifying nationals or H-1B.",
    requirements: ["Bachelor's in Architecture", "3+ years experience", "AutoCAD/Revit", "Portfolio required"],
    salary: "$70,000 - $90,000 USD per year",
    applyBy: "2026-08-25",
    type: "Full-time"
  },
  {
    id: 31,
    title: "Heavy Equipment Operator (LMIA)",
    company: "RockSolid Construction",
    location: "Fort McMurray, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "Operate excavators, bulldozers, and loaders on mining sites. Fly-in/fly-out. LMIA approved.",
    requirements: ["5+ years heavy equipment operation", "Safety certifications", "Physically demanding", "English CLB 5"],
    salary: "$35 - $45 CAD per hour",
    applyBy: "2026-08-05",
    type: "Full-time"
  },
  {
    id: 32,
    title: "Medical Laboratory Technologist (H-1B)",
    company: "LabCore Diagnostics",
    location: "Atlanta, USA",
    visaType: "USA H-1B Visa",
    description: "Perform diagnostic tests and analyze samples. ASCP certification required.",
    requirements: ["MLT degree", "ASCP certified", "2+ years experience", "English proficient"],
    salary: "$60,000 - $75,000 USD per year",
    applyBy: "2026-07-28",
    type: "Full-time"
  },
  {
    id: 33,
    title: "Dental Assistant (TN Visa)",
    company: "SmileCare Clinics",
    location: "Phoenix, USA",
    visaType: "USA TN Visa",
    description: "Assist dentists with procedures, sterilize equipment. TN for Canadian/Mexican graduates.",
    requirements: ["Dental assisting diploma", "State license if required", "1+ year experience", "English fluent"],
    salary: "$38,000 - $48,000 USD per year",
    applyBy: "2026-08-01",
    type: "Full-time"
  },
  {
    id: 34,
    title: "Painter & Decorator (LMIA)",
    company: "ColorCraft Finishes",
    location: "Winnipeg, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "Interior and exterior painting for residential and commercial projects. LMIA approved.",
    requirements: ["2+ years painting experience", "Knowledge of materials", "Attention to detail", "English CLB 4"],
    salary: "$22 - $27 CAD per hour",
    applyBy: "2026-07-22",
    type: "Full-time"
  },
  {
    id: 35,
    title: "Network Administrator (H-1B)",
    company: "CyberNet Solutions",
    location: "Austin, USA",
    visaType: "USA H-1B Visa",
    description: "Manage and troubleshoot network infrastructure. CCNA/CCNP preferred.",
    requirements: ["Bachelor's in IT", "3+ years network admin", "Cisco certification", "English fluent"],
    salary: "$75,000 - $95,000 USD per year",
    applyBy: "2026-08-12",
    type: "Full-time"
  },
  {
    id: 36,
    title: "Cook (LMIA)",
    company: "TimberWolf Lodge",
    location: "Banff, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "Prepare meals in a busy resort kitchen. LMIA approved. Staff accommodation available.",
    requirements: ["2+ years cooking experience", "Food Safe certificate", "Able to work weekends", "English CLB 4"],
    salary: "$17 - $20 CAD per hour",
    applyBy: "2026-07-15",
    type: "Full-time"
  },
  {
    id: 37,
    title: "Civil Engineering Technologist (LMIA)",
    company: "InfraDesign Inc.",
    location: "Ottawa, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "Assist engineers with designs and drafting using AutoCAD. LMIA approved.",
    requirements: ["Diploma in Civil Engineering Technology", "2+ years experience", "AutoCAD Civil 3D", "English CLB 6"],
    salary: "$55,000 - $68,000 CAD per year",
    applyBy: "2026-08-22",
    type: "Full-time"
  },
  {
    id: 38,
    title: "Hair Stylist (H-2B)",
    company: "Glamour Salon",
    location: "Las Vegas, USA",
    visaType: "USA H-2B Visa",
    description: "Provide hair cutting, coloring, and styling services. H-2B visa for experienced stylists.",
    requirements: ["Cosmetology license", "3+ years experience", "Portfolio", "English conversational"],
    salary: "$30,000 - $45,000 USD + tips",
    applyBy: "2026-07-10",
    type: "Full-time"
  },
  {
    id: 39,
    title: "Supply Chain Manager (L-1)",
    company: "GlobalSource Logistics",
    location: "Chicago, USA",
    visaType: "USA L-1 Visa",
    description: "Manage North American supply chain operations. Internal transfer from overseas.",
    requirements: ["Currently with GlobalSource", "5+ years supply chain", "Bachelor's degree", "English fluent"],
    salary: "$95,000 - $120,000 USD per year",
    applyBy: "2026-09-01",
    type: "Full-time"
  },
  {
    id: 40,
    title: "Physician (J-1 Waiver)",
    company: "Rural Health Clinic",
    location: "Kansas, USA",
    visaType: "USA J-1 Waiver (Conrad 30)",
    description: "Provide primary care in a medically underserved area. J-1 waiver offered.",
    requirements: ["MD/DO degree", "USMLE Steps", "Board eligible/certified", "English fluent"],
    salary: "$180,000 - $220,000 USD per year",
    applyBy: "2026-08-30",
    type: "Full-time"
  },
  {
    id: 41,
    title: "Electrician (LMIA Approved)",
    company: "LiveWire Electrical",
    location: "Surrey, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "Install and maintain electrical systems. Red Seal certification preferred. LMIA approved.",
    requirements: ["Journeyman electrician or 5+ years", "Red Seal (or eligible)", "Canadian electrical code knowledge", "English CLB 5"],
    salary: "$32 - $38 CAD per hour",
    applyBy: "2026-08-15",
    type: "Full-time"
  },
  {
    id: 42,
    title: "Translator (TN Visa)",
    company: "LinguaWorld Services",
    location: "New York, USA",
    visaType: "USA TN Visa",
    description: "Translate documents and provide interpretation for legal and medical clients. TN visa for Canadian/Mexican citizens.",
    requirements: ["Bachelor's degree in Translation or Linguistics", "3+ years experience", "Fluent in English + target language", "Certificate preferred"],
    salary: "$55,000 - $70,000 USD per year",
    applyBy: "2026-07-31",
    type: "Full-time"
  },
  {
    id: 43,
    title: "Roofing Technician (LMIA)",
    company: "SkyHigh Roofing",
    location: "Halifax, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "Install and repair roofing systems. LMIA approved for experienced roofers.",
    requirements: ["2+ years roofing experience", "Comfortable with heights", "Valid driver's license", "English CLB 4"],
    salary: "$25 - $30 CAD per hour",
    applyBy: "2026-08-01",
    type: "Full-time"
  },
  {
    id: 44,
    title: "Veterinary Technician (H-1B)",
    company: "AnimalCare Hospital",
    location: "Portland, USA",
    visaType: "USA H-1B Visa",
    description: "Assist veterinarians in surgery and animal care. Must be a licensed vet tech.",
    requirements: ["AVMA accredited vet tech degree", "VTNE certified", "2+ years experience", "English proficient"],
    salary: "$38,000 - $48,000 USD per year",
    applyBy: "2026-08-10",
    type: "Full-time"
  },
  {
    id: 45,
    title: "Industrial Painter (LMIA)",
    company: "ShieldCoatings Inc.",
    location: "Hamilton, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "Apply protective coatings to steel structures. LMIA approved.",
    requirements: ["3+ years industrial painting", "Knowledge of safety standards", "Able to work in confined spaces", "English CLB 4"],
    salary: "$24 - $29 CAD per hour",
    applyBy: "2026-08-05",
    type: "Full-time"
  },
  {
    id: 46,
    title: "Financial Analyst (TN Visa)",
    company: "CapitalWise Advisors",
    location: "Boston, USA",
    visaType: "USA TN Visa",
    description: "Analyze market trends and prepare investment reports. TN for Canadian/Mexican citizens with relevant degree.",
    requirements: ["Bachelor's in Finance or Economics", "2+ years experience", "CFA candidate preferred", "English fluent"],
    salary: "$70,000 - $90,000 USD per year",
    applyBy: "2026-08-20",
    type: "Full-time"
  },
  {
    id: 47,
    title: "Butcher (LMIA)",
    company: "Premium Meats Co.",
    location: "Regina, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "Cut, trim, and prepare meat products. LMIA approved for experienced butchers.",
    requirements: ["2+ years meat cutting experience", "Food safety certification", "Physically fit", "English CLB 4"],
    salary: "$20 - $24 CAD per hour",
    applyBy: "2026-07-25",
    type: "Full-time"
  },
  {
    id: 48,
    title: "Web Developer (H-1B)",
    company: "Digital Creations LLC",
    location: "Denver, USA",
    visaType: "USA H-1B Visa",
    description: "Build responsive websites and web applications using React and Node.js. H-1B sponsorship available.",
    requirements: ["2+ years web development", "React/Node.js", "Portfolio", "Bachelor's in CS or equivalent"],
    salary: "$75,000 - $95,000 USD per year",
    applyBy: "2026-08-15",
    type: "Full-time"
  },
  {
    id: 49,
    title: "Farm Supervisor (H-2A)",
    company: "Sunshine Farms",
    location: "Florida, USA",
    visaType: "USA H-2A Visa",
    description: "Supervise harvesting crews and manage farm operations. H-2A visa with supervisor role.",
    requirements: ["2+ years farm management", "Bilingual Spanish/English a plus", "Knowledge of agricultural practices", "Driver's license"],
    salary: "$40,000 - $55,000 USD per year",
    applyBy: "2026-06-30",
    type: "Full-time (Seasonal)"
  },
  {
    id: 50,
    title: "Security Guard (LMIA)",
    company: "SafeGuard Protection",
    location: "Toronto, Canada",
    visaType: "Canada Work Permit (LMIA)",
    description: "Monitor premises and ensure safety. Security license training provided. LMIA approved.",
    requirements: ["Security guard license (or willing to obtain)", "Criminal record check", "English CLB 5", "Flexible shifts"],
    salary: "$18 - $22 CAD per hour",
    applyBy: "2026-08-10",
    type: "Full-time"
  }
];
